[features]
seeds = false
[programs.localnet]
steelhands = "GJbHi5bV138ruTeHUWKLSV53HK57P7JNVFNcBXyPWc1L"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/cilantro/.config/solana/local.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
